name: Test and release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read
env:
  PYTHON_VERSION: "3.11.10"
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Test
        run: |
          uv run pytest


  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - lint-and-test
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          tag_name: ${{ steps.tag_version.outputs.new_tag }}



